### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Lenophie/MoniCAG#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Lenophie** [comment]
Hello,
This project being, at the moment, developed as a solution answering to a particular club needs, I would rather have its icon designed by one of its members.
Thanks for the proposal.
